version: '3'

name: 'npm'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - outside
      - internal
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  outside:
    external: true
    name: outside
  internal:
    external: true
    name: net_default
